version: "3.9"
services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "14268:14268"
      - "16686:16686"
      - "4318:4318"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.82.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

  zookeeper:
    image: debezium/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: quay.io/cloudhut/kowl:master
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_BROKERS: kafka:9092

  kafka-create-topics:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper
      - kafka
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                         cub kafka-ready -b kafka:9092 1 20 && \
                         kafka-topics --create --topic order-topic --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 && \
                         kafka-topics --create --topic history-topic --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 && \
                         sleep infinity'"
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored

  couchbase:
    image: couchbase/server:community-7.1.0-aarch64
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "8095:8095"
      - "8096:8096"
      - "11207:11207"
      - "11210:11210"
      - "11211:11211"
    environment:
      CLUSTER_NAME: "Cluster"
      USERNAME: "admin"
      PASSWORD: "password"
      BUCKET_NAME: "sample"
    volumes:
      - ./configure.sh:/configure.sh
    command: /bin/sh "/configure.sh"
